### ISSUE TITLE
Not working with Elixir 1.2

### ISSUE THREAD

**Issue by CraigCottingham** [igas/faker#46]
```
$ mix test
lib/faker/code.ex:1: warning: redefining module Faker.Code
lib/faker.ex:1: warning: redefining module Faker
lib/faker/avatar.ex:1: warning: redefining module Faker.Avatar
lib/faker/commerce.ex:1: warning: redefining module Faker.Commerce

== Compilation error on file lib/faker/app.ex ==
lib/faker/address.ex:1: warning: redefining module Faker.Address
** (CompileError) lib/faker/app.ex:2: cannot import Faker.sampler/2 because it doesn't exist
    (elixir) src/elixir_import.erl:68: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:18: :elixir_import.import/4

==> faker
could not compile dependency :faker, "mix compile" failed. You can recompile this dependency with "mix deps.compile faker", update it with "mix deps.update faker" or clean it with "mix deps.clean faker"
```
Are there changes in the works to get Faker working with Elixir 1.2?

**Comment by igas** [comment]
Hi, can you provide more information? Works on my machine and on travis https://travis-ci.org/igas/faker/builds/123650682

**Comment by CraigCottingham** [comment]
I apologize for prematurely filing an issue. I just created a brand new Phoenix application under Elixir 1.2, added Faker to it, and it is working fine. Apparently the problem I'm having in my original project is deeper than Faker.

**Comment by igas** [comment]
No worries, Craig.
